# Generated by Django 4.2 on 2026-01-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (€)')),
                ('image_front', models.ImageField(upload_to='products/front/', verbose_name='Image de face')),
                ('image_back', models.ImageField(upload_to='products/back/', verbose_name='Image au survol (hover)')),
                ('category', models.CharField(choices=[('VESTE', 'Vestes'), ('MANTEAU', 'Manteaux'), ('ACCESSOIRE', 'Accessoires')], default='VESTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['-created_at'],
            },
        ),
    ]
