# Generated by Django 4.2 on 2026-02-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexura', '0002_commande_commandeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
