# Generated by Django 4.2 on 2026-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexura', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VESTE', 'Vestes'), ('MANTEAU', 'Manteaux'), ('ACCESSOIRE', 'Accessoires'), ('ROBE', 'Robes'), ('CHAUSSURE', 'Chaussures'), ('PANTALON', 'pantalons')], default='VESTE', max_length=20),
        ),
    ]
